# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: adcfa14184854ffbdca0aa27def2f05ea146d231b2635babfa98d8baa49877b964efa59b07e89ed7d55ac1ae2fdd3f292ad56d3e50e7f69cff61471fd7747dbd

test:
  secret_key_base: bd4d3985ed50e29af8a7dec01c518b9f2d2f4ee5905f34cdcfa9944d1207dadc5ed4c099b2b795dd4e7d0ba80ac7c96a1fdd305fd2abd8fd90c6f3dc14efe882

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
